// lib/models/Invite.ts
// Signup invite codes generated by admins/webmasters.
// Required during signup if INVITE_ONLY mode is enabled.

import { ObjectId } from "mongodb";

export type InviteStatus = "active" | "used" | "expired" | "revoked";

export interface InviteDocument {
  _id?: ObjectId;

  code: string; // unique 6-char code e.g. "FF4DC1"
  status: InviteStatus;

  createdBy: ObjectId; // → Vault._id of admin/webmaster

  // Optional targeting
  note?: string; // e.g. "For UNIZIK batch 2026"
  maxUses: number; // 1 = single-use, >1 = multi-use
  useCount: number; // how many times used so far

  expiresAt?: Date; // optional expiry

  createdAt: Date;
  updatedAt: Date;
}
