// lib/db/seeds/eventSeed.ts
// Seed script — creates sample events + default free TicketType for each.
// Run: npx ts-node --project tsconfig.json lib/db/seeds/eventSeed.ts

import { ObjectId } from "mongodb";
import { getDb } from "@/lib/mongodb";
import { EventDocument } from "@/lib/models/Events";
import { TicketTypeDocument } from "@/lib/models/ticketType";

const ADMIN_ID = new ObjectId(); // replace with a real admin ObjectId in production

const now = new Date();

const sampleEvents: Omit<EventDocument, "_id">[] = [
  {
    slug: "diuscadi-summit-2026",
    title: "DIUSCADI Annual Summit 2026",
    overview:
      "The flagship annual gathering of the DIUSCADI ecosystem. Connect, learn, and grow.",
    learningOutcomes: [
      "Network with industry professionals",
      "Attend workshops on tech and innovation",
      "Learn about leadership and soft skills",
    ],
    category: "Conference",
    tags: ["networking", "innovation", "leadership"],
    level: "Beginner",
    instructor: "DIUSCADI Leadership Team",
    requiredSkills: [],
    targetEduStatus: "ALL",
    locationScope: "national",
    format: "physical",
    location: {
      venue: "Transcorp Hilton Abuja",
      city: "Abuja",
      state: "FCT",
      country: "Nigeria",
      address: "1 Aguiyi Ironsi Street, Maitama",
    },
    eventDate: new Date("2026-06-15T09:00:00Z"),
    endDate: new Date("2026-06-16T18:00:00Z"),
    registrationDeadline: new Date("2026-06-10T23:59:59Z"),
    duration: "2 days",
    capacity: 500,
    image: "/images/events/summit-2026.jpg",
    status: "published",
    createdBy: ADMIN_ID,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "tech-skills-bootcamp-q2-2026",
    title: "Tech Skills Bootcamp Q2 2026",
    overview:
      "An intensive bootcamp covering programming, electronics, and design fundamentals.",
    learningOutcomes: [
      "Build a working project with real tools",
      "Collaborate with peers in a team environment",
      "Receive mentorship from committee leads",
    ],
    category: "Workshop",
    tags: ["tech", "programming", "design", "electronics"],
    level: "Intermediate",
    instructor: "Innovation Committee",
    requiredSkills: ["programming", "electronics", "design"],
    targetEduStatus: "STUDENT",
    locationScope: "local",
    format: "hybrid",
    location: {
      venue: "DIUSCADI Hub",
      city: "Benin City",
      state: "Edo",
      country: "Nigeria",
    },
    eventDate: new Date("2026-04-20T10:00:00Z"),
    endDate: new Date("2026-04-22T16:00:00Z"),
    registrationDeadline: new Date("2026-04-15T23:59:59Z"),
    duration: "3 days",
    capacity: 80,
    image: "/images/events/bootcamp-q2.jpg",
    status: "published",
    createdBy: ADMIN_ID,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "creative-writing-retreat-2026",
    title: "Creative Writing Retreat 2026",
    overview: "A weekend retreat for aspiring writers to sharpen their craft.",
    learningOutcomes: [
      "Master storytelling techniques",
      "Participate in writing exercises",
      "Receive feedback from established authors",
    ],
    category: "Workshop",
    tags: ["writing", "creativity", "literature"],
    level: "Beginner",
    instructor: "Nigerian Authors Guild",
    requiredSkills: [],
    targetEduStatus: "ALL",
    locationScope: "local",
    format: "physical",
    location: {
      venue: "Ikoyi Conference Centre",
      city: "Lagos",
      state: "Lagos",
      country: "Nigeria",
    },
    eventDate: new Date("2026-05-10T09:00:00Z"),
    endDate: new Date("2026-05-12T17:00:00Z"),
    registrationDeadline: new Date("2026-05-05T23:59:59Z"),
    duration: "3 days",
    capacity: 60,
    image: "/images/events/writing-retreat.jpg",
    status: "published",
    createdBy: ADMIN_ID,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "ai-and-ml-conference-2026",
    title: "AI & ML Conference 2026",
    overview:
      "Explore the latest developments in artificial intelligence and machine learning.",
    learningOutcomes: [
      "Understand AI trends",
      "Hands-on ML workshops",
      "Networking with AI experts",
    ],
    category: "Conference",
    tags: ["AI", "ML", "tech", "innovation"],
    level: "Advanced",
    instructor: "Tech Innovators Association",
    requiredSkills: ["programming", "math"],
    targetEduStatus: "ALL",
    locationScope: "national",
    format: "hybrid",
    location: {
      venue: "Eko Hotel & Suites",
      city: "Lagos",
      state: "Lagos",
      country: "Nigeria",
    },
    eventDate: new Date("2026-07-05T09:00:00Z"),
    endDate: new Date("2026-07-07T18:00:00Z"),
    registrationDeadline: new Date("2026-06-30T23:59:59Z"),
    duration: "3 days",
    capacity: 400,
    image: "/images/events/ai-ml.jpg",
    status: "published",
    createdBy: ADMIN_ID,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "digital-marketing-masterclass-2026",
    title: "Digital Marketing Masterclass 2026",
    overview: "Learn digital marketing strategies from top experts.",
    learningOutcomes: [
      "Social media optimization",
      "Email marketing campaigns",
      "Analytics-driven decisions",
    ],
    category: "Workshop",
    tags: ["marketing", "digital", "SEO"],
    level: "Intermediate",
    instructor: "Marketing Pros Nigeria",
    requiredSkills: [],
    targetEduStatus: "ALL",
    locationScope: "local",
    format: "virtual",
    location: {},
    eventDate: new Date("2026-03-15T09:00:00Z"),
    endDate: new Date("2026-03-15T17:00:00Z"),
    registrationDeadline: new Date("2026-03-10T23:59:59Z"),
    duration: "1 day",
    capacity: 150,
    image: "/images/events/digital-marketing.jpg",
    status: "published",
    createdBy: ADMIN_ID,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "blockchain-bootcamp-2026",
    title: "Blockchain Bootcamp 2026",
    overview: "Intensive bootcamp on blockchain development and applications.",
    learningOutcomes: [
      "Smart contract development",
      "Decentralized app deployment",
      "Blockchain security principles",
    ],
    category: "Workshop",
    tags: ["blockchain", "crypto", "tech"],
    level: "Advanced",
    instructor: "Crypto Devs NG",
    requiredSkills: ["programming", "finance basics"],
    targetEduStatus: "STUDENT",
    locationScope: "local",
    format: "physical",
    location: {
      venue: "Innovation Hub, Awka",
      city: "Awka",
      state: "Anambra",
      country: "Nigeria",
    },
    eventDate: new Date("2026-08-01T10:00:00Z"),
    endDate: new Date("2026-08-05T17:00:00Z"),
    registrationDeadline: new Date("2026-07-25T23:59:59Z"),
    duration: "5 days",
    capacity: 70,
    image: "/images/events/blockchain.jpg",
    status: "published",
    createdBy: ADMIN_ID,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "entrepreneurship-summit-2026",
    title: "Entrepreneurship Summit 2026",
    overview: "A gathering for aspiring and established entrepreneurs.",
    learningOutcomes: [
      "Pitching to investors",
      "Scaling small businesses",
      "Networking with startups",
    ],
    category: "Conference",
    tags: ["business", "entrepreneurship", "startups"],
    level: "Beginner",
    instructor: "SME Growth Hub",
    requiredSkills: [],
    targetEduStatus: "ALL",
    locationScope: "national",
    format: "physical",
    location: {
      venue: "Transcorp Hilton Abuja",
      city: "Abuja",
      state: "FCT",
      country: "Nigeria",
    },
    eventDate: new Date("2026-09-12T09:00:00Z"),
    endDate: new Date("2026-09-13T18:00:00Z"),
    registrationDeadline: new Date("2026-09-05T23:59:59Z"),
    duration: "2 days",
    capacity: 300,
    image: "/images/events/entrepreneurship.jpg",
    status: "published",
    createdBy: ADMIN_ID,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "photography-workshop-2026",
    title: "Photography Workshop 2026",
    overview:
      "Learn the art of photography, editing, and storytelling through images.",
    learningOutcomes: [
      "Master DSLR techniques",
      "Photo editing in Lightroom/Photoshop",
      "Create a personal portfolio",
    ],
    category: "Workshop",
    tags: ["photography", "creativity", "art"],
    level: "Beginner",
    instructor: "ProLens Academy",
    requiredSkills: [],
    targetEduStatus: "ALL",
    locationScope: "local",
    format: "physical",
    location: {
      venue: "Ikorodu Creative Hub",
      city: "Lagos",
      state: "Lagos",
      country: "Nigeria",
    },
    eventDate: new Date("2026-03-20T09:00:00Z"),
    endDate: new Date("2026-03-21T17:00:00Z"),
    registrationDeadline: new Date("2026-03-15T23:59:59Z"),
    duration: "2 days",
    capacity: 50,
    image: "/images/events/photography.jpg",
    status: "published",
    createdBy: ADMIN_ID,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "cybersecurity-summit-2026",
    title: "Cybersecurity Summit 2026",
    overview:
      "Dive deep into cybersecurity trends, tools, and threat mitigation strategies.",
    learningOutcomes: [
      "Hands-on cybersecurity labs",
      "Learn ethical hacking principles",
      "Network with industry professionals",
    ],
    category: "Conference",
    tags: ["cybersecurity", "tech", "security"],
    level: "Advanced",
    instructor: "CyberSec NG",
    requiredSkills: ["IT fundamentals", "programming"],
    targetEduStatus: "ALL",
    locationScope: "national",
    format: "hybrid",
    location: {
      venue: "Radisson Blu Hotel",
      city: "Port Harcourt",
      state: "Rivers",
      country: "Nigeria",
    },
    eventDate: new Date("2026-10-10T09:00:00Z"),
    endDate: new Date("2026-10-12T18:00:00Z"),
    registrationDeadline: new Date("2026-10-05T23:59:59Z"),
    duration: "3 days",
    capacity: 350,
    image: "/images/events/cybersecurity.jpg",
    status: "published",
    createdBy: ADMIN_ID,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "data-science-bootcamp-2026",
    title: "Data Science Bootcamp 2026",
    overview:
      "Learn data analysis, visualization, and machine learning techniques.",
    learningOutcomes: [
      "Python for data science",
      "Data visualization",
      "ML model deployment",
    ],
    category: "Workshop",
    tags: ["data", "analytics", "ML"],
    level: "Intermediate",
    instructor: "Analytics Hub NG",
    requiredSkills: ["Python", "math"],
    targetEduStatus: "STUDENT",
    locationScope: "local",
    format: "hybrid",
    location: {
      venue: "Innovation Hub, Enugu",
      city: "Enugu",
      state: "Enugu",
      country: "Nigeria",
    },
    eventDate: new Date("2026-06-01T10:00:00Z"),
    endDate: new Date("2026-06-05T17:00:00Z"),
    registrationDeadline: new Date("2026-05-25T23:59:59Z"),
    duration: "5 days",
    capacity: 60,
    image: "/images/events/data-science.jpg",
    status: "published",
    createdBy: ADMIN_ID,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "health-tech-summit-2026",
    title: "Health Tech Summit 2026",
    overview:
      "Exploring innovations at the intersection of technology and healthcare.",
    learningOutcomes: [
      "Telemedicine trends",
      "Health data analytics",
      "Medical AI applications",
    ],
    category: "Conference",
    tags: ["health", "tech", "innovation"],
    level: "Advanced",
    instructor: "HealthTech NG",
    requiredSkills: ["IT fundamentals"],
    targetEduStatus: "ALL",
    locationScope: "national",
    format: "hybrid",
    location: {
      venue: "Eko Convention Centre",
      city: "Lagos",
      state: "Lagos",
      country: "Nigeria",
    },
    eventDate: new Date("2026-11-12T09:00:00Z"),
    endDate: new Date("2026-11-14T18:00:00Z"),
    registrationDeadline: new Date("2026-11-05T23:59:59Z"),
    duration: "3 days",
    capacity: 300,
    image: "/images/events/health-tech.jpg",
    status: "published",
    createdBy: ADMIN_ID,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "fashion-design-workshop-2026",
    title: "Fashion Design Workshop 2026",
    overview: "Hands-on workshop for aspiring fashion designers.",
    learningOutcomes: [
      "Garment creation",
      "Trend forecasting",
      "Portfolio development",
    ],
    category: "Workshop",
    tags: ["fashion", "design", "creativity"],
    level: "Beginner",
    instructor: "Lagos Fashion Hub",
    requiredSkills: [],
    targetEduStatus: "ALL",
    locationScope: "local",
    format: "physical",
    location: {
      venue: "Lagos Design Centre",
      city: "Lagos",
      state: "Lagos",
      country: "Nigeria",
    },
    eventDate: new Date("2026-04-10T09:00:00Z"),
    endDate: new Date("2026-04-11T17:00:00Z"),
    registrationDeadline: new Date("2026-04-05T23:59:59Z"),
    duration: "2 days",
    capacity: 50,
    image: "/images/events/fashion.jpg",
    status: "published",
    createdBy: ADMIN_ID,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "film-making-masterclass-2026",
    title: "Film Making Masterclass 2026",
    overview: "Learn the art of film making from scripting to post-production.",
    learningOutcomes: [
      "Storyboarding and scripting",
      "Camera techniques",
      "Editing and post-production",
    ],
    category: "Workshop",
    tags: ["film", "media", "creativity"],
    level: "Intermediate",
    instructor: "Nollywood Academy",
    requiredSkills: ["basic video editing"],
    targetEduStatus: "ALL",
    locationScope: "local",
    format: "physical",
    location: {
      venue: "Lagos Media Centre",
      city: "Lagos",
      state: "Lagos",
      country: "Nigeria",
    },
    eventDate: new Date("2026-05-18T09:00:00Z"),
    endDate: new Date("2026-05-22T17:00:00Z"),
    registrationDeadline: new Date("2026-05-12T23:59:59Z"),
    duration: "5 days",
    capacity: 60,
    image: "/images/events/filmmaking.jpg",
    status: "published",
    createdBy: ADMIN_ID,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "renewable-energy-conference-2026",
    title: "Renewable Energy Conference 2026",
    overview: "Discussing innovations and policies in renewable energy.",
    learningOutcomes: [
      "Sustainable energy solutions",
      "Policy and market trends",
      "Networking with energy experts",
    ],
    category: "Conference",
    tags: ["energy", "sustainability", "tech"],
    level: "Advanced",
    instructor: "Energy Forum Nigeria",
    requiredSkills: [],
    targetEduStatus: "ALL",
    locationScope: "national",
    format: "hybrid",
    location: {
      venue: "Transcorp Hilton Abuja",
      city: "Abuja",
      state: "FCT",
      country: "Nigeria",
    },
    eventDate: new Date("2026-12-01T09:00:00Z"),
    endDate: new Date("2026-12-03T18:00:00Z"),
    registrationDeadline: new Date("2026-11-25T23:59:59Z"),
    duration: "3 days",
    capacity: 300,
    image: "/images/events/renewable-energy.jpg",
    status: "published",
    createdBy: ADMIN_ID,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "startup-pitch-competition-2026",
    title: "Startup Pitch Competition 2026",
    overview:
      "A competition for early-stage startups to pitch ideas to investors.",
    learningOutcomes: [
      "Pitch deck creation",
      "Investor feedback",
      "Networking opportunities",
    ],
    category: "Competition",
    tags: ["startups", "business", "pitch"],
    level: "Intermediate",
    instructor: "Startup Hub NG",
    requiredSkills: [],
    targetEduStatus: "STUDENT",
    locationScope: "local",
    format: "physical",
    location: {
      venue: "Tech Hub, Owerri",
      city: "Owerri",
      state: "Imo",
      country: "Nigeria",
    },
    eventDate: new Date("2026-08-15T09:00:00Z"),
    endDate: new Date("2026-08-16T17:00:00Z"),
    registrationDeadline: new Date("2026-08-10T23:59:59Z"),
    duration: "2 days",
    capacity: 100,
    image: "/images/events/startup-pitch.jpg",
    status: "published",
    createdBy: ADMIN_ID,
    createdAt: now,
    updatedAt: now,
  },
];

async function seed() {
  const db = await getDb();

  for (const eventData of sampleEvents) {
    // Upsert by slug to make seed idempotent
    const result = await db
      .collection<EventDocument>("events")
      .findOneAndUpdate(
        { slug: eventData.slug },
        { $setOnInsert: eventData },
        { upsert: true, returnDocument: "after" },
      );

    const eventId = result?._id;
    if (!eventId) {
      console.warn(`Skipped (already exists): ${eventData.slug}`);
      continue;
    }

    // Create default free TicketType
    const ticketType: Omit<TicketTypeDocument, "_id"> = {
      eventId,
      name: "Free",
      price: 0,
      currency: "NGN",
      maxQuantity: eventData.capacity,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    };

    await db
      .collection<TicketTypeDocument>("ticketTypes")
      .updateOne(
        { eventId, name: "Free" },
        { $setOnInsert: ticketType },
        { upsert: true },
      );

    console.log(`✓ Seeded: ${eventData.title}`);
  }

  console.log("\n✅ Event seed complete.");
  process.exit(0);
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
